# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f347c92638221eb8c43d4d8a61efe59444b5fae625c2390384534b60ca92e165a6d7995b67f7c56cb48af8f8443deab5831803c9a4a310af8a109b9764e5455

test:
  secret_key_base: 97d6f804c6e471b2fd870d136c3b05cfc4c85d5f6770c6e607b44aa8b4e6535674dd38b5e5d868b228d1fafba7d9aeeb4dca0b2dc364f672d9cf91e8cdf3a1c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
